[package]
name = "sieve-rs"
description = "Sieve filter interpreter for Rust"
authors = [ "Stalwart Labs <hello@stalw.art>"]
repository = "https://github.com/stalwartlabs/sieve"
homepage = "https://github.com/stalwartlabs/sieve"
license = "AGPL-3.0-only"
keywords = ["sieve", "interpreter", "compiler", "email", "mail"]
categories = ["email", "compilers"]
readme = "README.md"
version = "1.0.0"
edition = "2024"

[lib]
name = "sieve"
doctest = false

[dependencies]
mail-parser = { version = "0.11", features = ["full_encoding"] }
fancy-regex = "0.19.0"
bumpalo = { version = "3.20", features = ["collections"] }
memchr = "2.7"
smallvec = "1.16"
hashbrown = "0.17.1"
serde = { version = "1.0", features = ["derive", "rc"], optional = true }

[target.'cfg(not(target_pointer_width = "32"))'.dependencies]
hashify = { version = "0.2" }

[target.'cfg(target_pointer_width = "32")'.dependencies]
hashify = { version = "0.2", features = ["force-32bit"] }

[target.'cfg(not(all(target_family = "wasm", target_os = "unknown")))'.dependencies]
mail-builder = { version = "0.5" }
ahash = { version = "0.8.0" }

[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]
mail-builder = { version = "0.5", default-features = false }
ahash = { version = "0.8.0", default-features = false, features = ["std", "compile-time-rng"] }

[dev-dependencies]
mail-parser = { version = "0.11", features = ["full_encoding", "serde"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
evalexpr = "13.1.0"

[features]
default = []
serde = ["dep:serde", "mail-parser/serde"]
